export const RoutingLinks = {
  HOME: 'home',
  AMOUNTTOPAY: 'amountToPay',
  MAKEAPAYMENT: 'makeapayment',
  OTPSCREEN: 'otpscreen',
  CONFIRMATION: 'confirmation',
  ADDBILLS: 'addbills',
  SELECTPRIMARYACCOUNT: 'selectprimaryaccount',
  TODO: 'todo',
  STARTSCREEN: 'startscreen',
  PERMISSIONS: 'permissions',
  SETUPPAYMENT: 'setuppayment',
  ZELLESTARTSCREEN: 'zellestartscreen',
  ZELLEPERMISSIONS: 'zellepermissions',
  ZELLESETUPPAYMENT: 'zellesetuppayment',
  FINDMOREBILLS: "findmorebills",
  SELECTADDBILLS: "selectaddbills",
  SUCCESSFAILURE: "successfailure",
  DASHBOARD: 'dashboard',
  SUCCESSSCREEN: 'successscreen',
  GENERALONBOARDINGSUCCESSSCREEN: 'generalonboardingsuccessscreen',
  BILLERCONFIRMATION: 'billerconfirmation',
  ZELLEPAYAUTHENTICATION: 'zellepayauthentication',
  BILLPAYAUTHENTICATION: 'billpayauthentication',
};
